print('Comparador de números\n')
n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número:  '))
n3 = int(input('Digite o terceiro número: '))
lista = sorted((n1, n2, n3))
print('O maior número é: {}'.format(lista[2]))
print(' O menor número é: {}'.format(lista[0]))